// Auto-generated. Do not edit!

// (in-package behavior_tree.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class TurningAroundGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.rotation_direction = null;
    }
    else {
      if (initObj.hasOwnProperty('rotation_direction')) {
        this.rotation_direction = initObj.rotation_direction
      }
      else {
        this.rotation_direction = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TurningAroundGoal
    // Serialize message field [rotation_direction]
    bufferOffset = _serializer.uint32(obj.rotation_direction, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type TurningAroundGoal
    let len;
    let data = new TurningAroundGoal(null);
    // Deserialize message field [rotation_direction]
    data.rotation_direction = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'behavior_tree/TurningAroundGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '06a633bcc37319791ff50c2da73ac867';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the goal
    uint32 rotation_direction 
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TurningAroundGoal(null);
    if (msg.rotation_direction !== undefined) {
      resolved.rotation_direction = msg.rotation_direction;
    }
    else {
      resolved.rotation_direction = 0
    }

    return resolved;
    }
};

module.exports = TurningAroundGoal;
