// Auto-generated. Do not edit!

// (in-package behavior_tree.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class TurningAroundFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.rotation_status = null;
    }
    else {
      if (initObj.hasOwnProperty('rotation_status')) {
        this.rotation_status = initObj.rotation_status
      }
      else {
        this.rotation_status = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TurningAroundFeedback
    // Serialize message field [rotation_status]
    bufferOffset = _serializer.float32(obj.rotation_status, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type TurningAroundFeedback
    let len;
    let data = new TurningAroundFeedback(null);
    // Deserialize message field [rotation_status]
    data.rotation_status = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'behavior_tree/TurningAroundFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '8d86daa292f3a880c6162663bc037e95';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    float32 rotation_status
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TurningAroundFeedback(null);
    if (msg.rotation_status !== undefined) {
      resolved.rotation_status = msg.rotation_status;
    }
    else {
      resolved.rotation_status = 0.0
    }

    return resolved;
    }
};

module.exports = TurningAroundFeedback;
