// Auto-generated. Do not edit!

// (in-package behavior_tree.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class TurningAroundResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.rotating_time = null;
    }
    else {
      if (initObj.hasOwnProperty('rotating_time')) {
        this.rotating_time = initObj.rotating_time
      }
      else {
        this.rotating_time = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type TurningAroundResult
    // Serialize message field [rotating_time]
    bufferOffset = _serializer.uint32(obj.rotating_time, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type TurningAroundResult
    let len;
    let data = new TurningAroundResult(null);
    // Deserialize message field [rotating_time]
    data.rotating_time = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'behavior_tree/TurningAroundResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '9e884966b1d8cea170e6a1b0ac01e559';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    uint32 rotating_time # 1 round, 2round or so on
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new TurningAroundResult(null);
    if (msg.rotating_time !== undefined) {
      resolved.rotating_time = msg.rotating_time;
    }
    else {
      resolved.rotating_time = 0
    }

    return resolved;
    }
};

module.exports = TurningAroundResult;
