# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from serial_imu/Imu_0x91_msg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import serial_imu.msg
import std_msgs.msg

class Imu_0x91_msg(genpy.Message):
  _md5sum = "bf1a29bdfa7a4861f3dcfb7c14758970"
  _type = "serial_imu/Imu_0x91_msg"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """#90 91 data_package
Header header
Imu_data_package imu_data


================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: serial_imu/Imu_data_package
uint8 tag
uint8 bitmap
uint8 id
float32 prs
uint32 time
uint32 frame_rate
float32 acc_x
float32 acc_y
float32 acc_z
float32 gyr_x
float32 gyr_y
float32 gyr_z
float32 mag_x
float32 mag_y
float32 mag_z
float32 eul_r
float32 eul_p
float32 eul_y
float32 quat_w
float32 quat_x
float32 quat_y
float32 quat_z
"""
  __slots__ = ['header','imu_data']
  _slot_types = ['std_msgs/Header','serial_imu/Imu_data_package']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,imu_data

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Imu_0x91_msg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.imu_data is None:
        self.imu_data = serial_imu.msg.Imu_data_package()
    else:
      self.header = std_msgs.msg.Header()
      self.imu_data = serial_imu.msg.Imu_data_package()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3Bf2I16f().pack(_x.imu_data.tag, _x.imu_data.bitmap, _x.imu_data.id, _x.imu_data.prs, _x.imu_data.time, _x.imu_data.frame_rate, _x.imu_data.acc_x, _x.imu_data.acc_y, _x.imu_data.acc_z, _x.imu_data.gyr_x, _x.imu_data.gyr_y, _x.imu_data.gyr_z, _x.imu_data.mag_x, _x.imu_data.mag_y, _x.imu_data.mag_z, _x.imu_data.eul_r, _x.imu_data.eul_p, _x.imu_data.eul_y, _x.imu_data.quat_w, _x.imu_data.quat_x, _x.imu_data.quat_y, _x.imu_data.quat_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.imu_data is None:
        self.imu_data = serial_imu.msg.Imu_data_package()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 79
      (_x.imu_data.tag, _x.imu_data.bitmap, _x.imu_data.id, _x.imu_data.prs, _x.imu_data.time, _x.imu_data.frame_rate, _x.imu_data.acc_x, _x.imu_data.acc_y, _x.imu_data.acc_z, _x.imu_data.gyr_x, _x.imu_data.gyr_y, _x.imu_data.gyr_z, _x.imu_data.mag_x, _x.imu_data.mag_y, _x.imu_data.mag_z, _x.imu_data.eul_r, _x.imu_data.eul_p, _x.imu_data.eul_y, _x.imu_data.quat_w, _x.imu_data.quat_x, _x.imu_data.quat_y, _x.imu_data.quat_z,) = _get_struct_3Bf2I16f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3Bf2I16f().pack(_x.imu_data.tag, _x.imu_data.bitmap, _x.imu_data.id, _x.imu_data.prs, _x.imu_data.time, _x.imu_data.frame_rate, _x.imu_data.acc_x, _x.imu_data.acc_y, _x.imu_data.acc_z, _x.imu_data.gyr_x, _x.imu_data.gyr_y, _x.imu_data.gyr_z, _x.imu_data.mag_x, _x.imu_data.mag_y, _x.imu_data.mag_z, _x.imu_data.eul_r, _x.imu_data.eul_p, _x.imu_data.eul_y, _x.imu_data.quat_w, _x.imu_data.quat_x, _x.imu_data.quat_y, _x.imu_data.quat_z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.imu_data is None:
        self.imu_data = serial_imu.msg.Imu_data_package()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 79
      (_x.imu_data.tag, _x.imu_data.bitmap, _x.imu_data.id, _x.imu_data.prs, _x.imu_data.time, _x.imu_data.frame_rate, _x.imu_data.acc_x, _x.imu_data.acc_y, _x.imu_data.acc_z, _x.imu_data.gyr_x, _x.imu_data.gyr_y, _x.imu_data.gyr_z, _x.imu_data.mag_x, _x.imu_data.mag_y, _x.imu_data.mag_z, _x.imu_data.eul_r, _x.imu_data.eul_p, _x.imu_data.eul_y, _x.imu_data.quat_w, _x.imu_data.quat_x, _x.imu_data.quat_y, _x.imu_data.quat_z,) = _get_struct_3Bf2I16f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3Bf2I16f = None
def _get_struct_3Bf2I16f():
    global _struct_3Bf2I16f
    if _struct_3Bf2I16f is None:
        _struct_3Bf2I16f = struct.Struct("<3Bf2I16f")
    return _struct_3Bf2I16f
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
