(cl:in-package serial_imu-msg)
(cl:export '(TAG-VAL
          TAG
          BITMAP-VAL
          BITMAP
          ID-VAL
          ID
          PRS-VAL
          PRS
          TIME-VAL
          TIME
          FRAME_RATE-VAL
          FRAME_RATE
          ACC_X-VAL
          ACC_X
          ACC_Y-VAL
          ACC_Y
          ACC_Z-VAL
          ACC_Z
          GYR_X-VAL
          GYR_X
          GYR_Y-VAL
          GYR_Y
          GYR_Z-VAL
          GYR_Z
          MAG_X-VAL
          MAG_X
          MAG_Y-VAL
          MAG_Y
          MAG_Z-VAL
          MAG_Z
          EUL_R-VAL
          EUL_R
          EUL_P-VAL
          EUL_P
          EUL_Y-VAL
          EUL_Y
          QUAT_W-VAL
          QUAT_W
          QUAT_X-VAL
          QUAT_X
          QUAT_Y-VAL
          QUAT_Y
          QUAT_Z-VAL
          QUAT_Z
))