# For a direct USB cable connection, the port name is typically
# /dev/ttyACM# where is # is a number such as 0, 1, 2, etc
# For a wireless connection like XBee, the port is typically
# /dev/ttyUSB# where # is a number such as 0, 1, 2, etc.

port: "/dev/MyArduino"
baud: 115200
timeout: 0.1

rate: 30
sensorstate_rate: 30

use_base_controller: True
base_controller_rate: 30

# For a robot that uses base_footprint, change base_frame to base_footprint
base_frame: base_footprint

# === Robot drivetrain parameters
wheel_diameter: 0.1

#How to calculate 'wheel_track'? For a 3WD base, it is the distance from one wheel to the center of the base.
wheel_track: 0.12

encoder_resolution: 24 # CPR 12 * 2 
gear_reduction: 64 #reducting rate
#motors_reversed: True

# === PID parameters
Kp: 28
Kd: 23
Ki: 0
Ko: 50
accel_limit: 2.0

# === Sensor definitions.  Examples only - edit for your robot.
#     Sensor type can be one of the follow (case sensitive!):
#	  * Ping
#	  * GP2D12
#	  * Analog
#	  * Digital
#	  * PololuMotorCurrent
#	  * PhidgetsVoltage
#	  * PhidgetsCurrent (20 Amp, DC)



sensors: {
  #motor_current_left:   {pin: 0, type: PololuMotorCurrent, rate: 5},
  #motor_current_right:  {pin: 1, type: PololuMotorCurrent, rate: 5},
  #ir_front_center:      {pin: 2, type: GP2D12, rate: 10},
  #sonar_front_center:   {pin: 5, type: Ping, rate: 10},
  IRleft:          {pin: 18, type: Digital, rate: 10},
  IRright:          {pin: 17, type: Digital, rate: 10},
  IRback:          {pin: 16, type: Digital, rate: 10},
  arduino_led:          {pin: 13, type: Digital, rate: 1, direction: output}
}
