; Auto-generated. Do not edit!


(cl:in-package behavior_tree-msg)


;//! \htmlinclude RobotStatusControllerFeedback.msg.html

(cl:defclass <RobotStatusControllerFeedback> (roslisp-msg-protocol:ros-message)
  ((percent_complete
    :reader percent_complete
    :initarg :percent_complete
    :type cl:float
    :initform 0.0))
)

(cl:defclass RobotStatusControllerFeedback (<RobotStatusControllerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RobotStatusControllerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RobotStatusControllerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name behavior_tree-msg:<RobotStatusControllerFeedback> is deprecated: use behavior_tree-msg:RobotStatusControllerFeedback instead.")))

(cl:ensure-generic-function 'percent_complete-val :lambda-list '(m))
(cl:defmethod percent_complete-val ((m <RobotStatusControllerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader behavior_tree-msg:percent_complete-val is deprecated.  Use behavior_tree-msg:percent_complete instead.")
  (percent_complete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RobotStatusControllerFeedback>) ostream)
  "Serializes a message object of type '<RobotStatusControllerFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'percent_complete))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RobotStatusControllerFeedback>) istream)
  "Deserializes a message object of type '<RobotStatusControllerFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent_complete) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RobotStatusControllerFeedback>)))
  "Returns string type for a message object of type '<RobotStatusControllerFeedback>"
  "behavior_tree/RobotStatusControllerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RobotStatusControllerFeedback)))
  "Returns string type for a message object of type 'RobotStatusControllerFeedback"
  "behavior_tree/RobotStatusControllerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RobotStatusControllerFeedback>)))
  "Returns md5sum for a message object of type '<RobotStatusControllerFeedback>"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RobotStatusControllerFeedback)))
  "Returns md5sum for a message object of type 'RobotStatusControllerFeedback"
  "d342375c60a5a58d3bc32664070a1368")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RobotStatusControllerFeedback>)))
  "Returns full string definition for message of type '<RobotStatusControllerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 percent_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RobotStatusControllerFeedback)))
  "Returns full string definition for message of type 'RobotStatusControllerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%float32 percent_complete~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RobotStatusControllerFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RobotStatusControllerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'RobotStatusControllerFeedback
    (cl:cons ':percent_complete (percent_complete msg))
))
