; Auto-generated. Do not edit!


(cl:in-package behavior_tree-msg)


;//! \htmlinclude RobotStatusControllerGoal.msg.html

(cl:defclass <RobotStatusControllerGoal> (roslisp-msg-protocol:ros-message)
  ((dishwasher_id
    :reader dishwasher_id
    :initarg :dishwasher_id
    :type cl:integer
    :initform 0))
)

(cl:defclass RobotStatusControllerGoal (<RobotStatusControllerGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RobotStatusControllerGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RobotStatusControllerGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name behavior_tree-msg:<RobotStatusControllerGoal> is deprecated: use behavior_tree-msg:RobotStatusControllerGoal instead.")))

(cl:ensure-generic-function 'dishwasher_id-val :lambda-list '(m))
(cl:defmethod dishwasher_id-val ((m <RobotStatusControllerGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader behavior_tree-msg:dishwasher_id-val is deprecated.  Use behavior_tree-msg:dishwasher_id instead.")
  (dishwasher_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RobotStatusControllerGoal>) ostream)
  "Serializes a message object of type '<RobotStatusControllerGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'dishwasher_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'dishwasher_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'dishwasher_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'dishwasher_id)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RobotStatusControllerGoal>) istream)
  "Deserializes a message object of type '<RobotStatusControllerGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'dishwasher_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'dishwasher_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'dishwasher_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'dishwasher_id)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RobotStatusControllerGoal>)))
  "Returns string type for a message object of type '<RobotStatusControllerGoal>"
  "behavior_tree/RobotStatusControllerGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RobotStatusControllerGoal)))
  "Returns string type for a message object of type 'RobotStatusControllerGoal"
  "behavior_tree/RobotStatusControllerGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RobotStatusControllerGoal>)))
  "Returns md5sum for a message object of type '<RobotStatusControllerGoal>"
  "65bd9e09a531006f4ecdeabe719004b9")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RobotStatusControllerGoal)))
  "Returns md5sum for a message object of type 'RobotStatusControllerGoal"
  "65bd9e09a531006f4ecdeabe719004b9")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RobotStatusControllerGoal>)))
  "Returns full string definition for message of type '<RobotStatusControllerGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 dishwasher_id  # Specify which dishwasher we want to use~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RobotStatusControllerGoal)))
  "Returns full string definition for message of type 'RobotStatusControllerGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 dishwasher_id  # Specify which dishwasher we want to use~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RobotStatusControllerGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RobotStatusControllerGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'RobotStatusControllerGoal
    (cl:cons ':dishwasher_id (dishwasher_id msg))
))
