; Auto-generated. Do not edit!


(cl:in-package behavior_tree-msg)


;//! \htmlinclude RobotStatusControllerResult.msg.html

(cl:defclass <RobotStatusControllerResult> (roslisp-msg-protocol:ros-message)
  ((total_dishes_cleaned
    :reader total_dishes_cleaned
    :initarg :total_dishes_cleaned
    :type cl:integer
    :initform 0))
)

(cl:defclass RobotStatusControllerResult (<RobotStatusControllerResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RobotStatusControllerResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RobotStatusControllerResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name behavior_tree-msg:<RobotStatusControllerResult> is deprecated: use behavior_tree-msg:RobotStatusControllerResult instead.")))

(cl:ensure-generic-function 'total_dishes_cleaned-val :lambda-list '(m))
(cl:defmethod total_dishes_cleaned-val ((m <RobotStatusControllerResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader behavior_tree-msg:total_dishes_cleaned-val is deprecated.  Use behavior_tree-msg:total_dishes_cleaned instead.")
  (total_dishes_cleaned m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RobotStatusControllerResult>) ostream)
  "Serializes a message object of type '<RobotStatusControllerResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_dishes_cleaned)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'total_dishes_cleaned)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'total_dishes_cleaned)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'total_dishes_cleaned)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RobotStatusControllerResult>) istream)
  "Deserializes a message object of type '<RobotStatusControllerResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'total_dishes_cleaned)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'total_dishes_cleaned)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'total_dishes_cleaned)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'total_dishes_cleaned)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RobotStatusControllerResult>)))
  "Returns string type for a message object of type '<RobotStatusControllerResult>"
  "behavior_tree/RobotStatusControllerResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RobotStatusControllerResult)))
  "Returns string type for a message object of type 'RobotStatusControllerResult"
  "behavior_tree/RobotStatusControllerResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RobotStatusControllerResult>)))
  "Returns md5sum for a message object of type '<RobotStatusControllerResult>"
  "58faa44dda59c6545bea63ff57491cbe")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RobotStatusControllerResult)))
  "Returns md5sum for a message object of type 'RobotStatusControllerResult"
  "58faa44dda59c6545bea63ff57491cbe")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RobotStatusControllerResult>)))
  "Returns full string definition for message of type '<RobotStatusControllerResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 total_dishes_cleaned~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RobotStatusControllerResult)))
  "Returns full string definition for message of type 'RobotStatusControllerResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 total_dishes_cleaned~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RobotStatusControllerResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RobotStatusControllerResult>))
  "Converts a ROS message object to a list"
  (cl:list 'RobotStatusControllerResult
    (cl:cons ':total_dishes_cleaned (total_dishes_cleaned msg))
))
