; Auto-generated. Do not edit!


(cl:in-package behavior_tree-msg)


;//! \htmlinclude TurningAroundResult.msg.html

(cl:defclass <TurningAroundResult> (roslisp-msg-protocol:ros-message)
  ((rotating_time
    :reader rotating_time
    :initarg :rotating_time
    :type cl:integer
    :initform 0))
)

(cl:defclass TurningAroundResult (<TurningAroundResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TurningAroundResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TurningAroundResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name behavior_tree-msg:<TurningAroundResult> is deprecated: use behavior_tree-msg:TurningAroundResult instead.")))

(cl:ensure-generic-function 'rotating_time-val :lambda-list '(m))
(cl:defmethod rotating_time-val ((m <TurningAroundResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader behavior_tree-msg:rotating_time-val is deprecated.  Use behavior_tree-msg:rotating_time instead.")
  (rotating_time m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TurningAroundResult>) ostream)
  "Serializes a message object of type '<TurningAroundResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'rotating_time)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'rotating_time)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'rotating_time)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'rotating_time)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TurningAroundResult>) istream)
  "Deserializes a message object of type '<TurningAroundResult>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'rotating_time)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'rotating_time)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'rotating_time)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'rotating_time)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TurningAroundResult>)))
  "Returns string type for a message object of type '<TurningAroundResult>"
  "behavior_tree/TurningAroundResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TurningAroundResult)))
  "Returns string type for a message object of type 'TurningAroundResult"
  "behavior_tree/TurningAroundResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TurningAroundResult>)))
  "Returns md5sum for a message object of type '<TurningAroundResult>"
  "9e884966b1d8cea170e6a1b0ac01e559")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TurningAroundResult)))
  "Returns md5sum for a message object of type 'TurningAroundResult"
  "9e884966b1d8cea170e6a1b0ac01e559")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TurningAroundResult>)))
  "Returns full string definition for message of type '<TurningAroundResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 rotating_time # 1 round, 2round or so on~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TurningAroundResult)))
  "Returns full string definition for message of type 'TurningAroundResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%uint32 rotating_time # 1 round, 2round or so on~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TurningAroundResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TurningAroundResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TurningAroundResult
    (cl:cons ':rotating_time (rotating_time msg))
))
