; Auto-generated. Do not edit!


(cl:in-package behavior_tree-msg)


;//! \htmlinclude TurningAroundGoal.msg.html

(cl:defclass <TurningAroundGoal> (roslisp-msg-protocol:ros-message)
  ((rotation_direction
    :reader rotation_direction
    :initarg :rotation_direction
    :type cl:integer
    :initform 0))
)

(cl:defclass TurningAroundGoal (<TurningAroundGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TurningAroundGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TurningAroundGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name behavior_tree-msg:<TurningAroundGoal> is deprecated: use behavior_tree-msg:TurningAroundGoal instead.")))

(cl:ensure-generic-function 'rotation_direction-val :lambda-list '(m))
(cl:defmethod rotation_direction-val ((m <TurningAroundGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader behavior_tree-msg:rotation_direction-val is deprecated.  Use behavior_tree-msg:rotation_direction instead.")
  (rotation_direction m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TurningAroundGoal>) ostream)
  "Serializes a message object of type '<TurningAroundGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'rotation_direction)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'rotation_direction)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'rotation_direction)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'rotation_direction)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TurningAroundGoal>) istream)
  "Deserializes a message object of type '<TurningAroundGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'rotation_direction)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'rotation_direction)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'rotation_direction)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'rotation_direction)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TurningAroundGoal>)))
  "Returns string type for a message object of type '<TurningAroundGoal>"
  "behavior_tree/TurningAroundGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TurningAroundGoal)))
  "Returns string type for a message object of type 'TurningAroundGoal"
  "behavior_tree/TurningAroundGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TurningAroundGoal>)))
  "Returns md5sum for a message object of type '<TurningAroundGoal>"
  "06a633bcc37319791ff50c2da73ac867")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TurningAroundGoal)))
  "Returns md5sum for a message object of type 'TurningAroundGoal"
  "06a633bcc37319791ff50c2da73ac867")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TurningAroundGoal>)))
  "Returns full string definition for message of type '<TurningAroundGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 rotation_direction ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TurningAroundGoal)))
  "Returns full string definition for message of type 'TurningAroundGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint32 rotation_direction ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TurningAroundGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TurningAroundGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TurningAroundGoal
    (cl:cons ':rotation_direction (rotation_direction msg))
))
