// Generated by gencpp from file behavior_tree/RobotStatusControllerFeedback.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_TREE_MESSAGE_ROBOTSTATUSCONTROLLERFEEDBACK_H
#define BEHAVIOR_TREE_MESSAGE_ROBOTSTATUSCONTROLLERFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behavior_tree
{
template <class ContainerAllocator>
struct RobotStatusControllerFeedback_
{
  typedef RobotStatusControllerFeedback_<ContainerAllocator> Type;

  RobotStatusControllerFeedback_()
    : percent_complete(0.0)  {
    }
  RobotStatusControllerFeedback_(const ContainerAllocator& _alloc)
    : percent_complete(0.0)  {
  (void)_alloc;
    }



   typedef float _percent_complete_type;
  _percent_complete_type percent_complete;





  typedef boost::shared_ptr< ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStatusControllerFeedback_

typedef ::behavior_tree::RobotStatusControllerFeedback_<std::allocator<void> > RobotStatusControllerFeedback;

typedef boost::shared_ptr< ::behavior_tree::RobotStatusControllerFeedback > RobotStatusControllerFeedbackPtr;
typedef boost::shared_ptr< ::behavior_tree::RobotStatusControllerFeedback const> RobotStatusControllerFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator1> & lhs, const ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.percent_complete == rhs.percent_complete;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator1> & lhs, const ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior_tree

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d342375c60a5a58d3bc32664070a1368";
  }

  static const char* value(const ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd342375c60a5a58dULL;
  static const uint64_t static_value2 = 0x3bc32664070a1368ULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_tree/RobotStatusControllerFeedback";
  }

  static const char* value(const ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"float32 percent_complete\n"
;
  }

  static const char* value(const ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.percent_complete);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStatusControllerFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_tree::RobotStatusControllerFeedback_<ContainerAllocator>& v)
  {
    s << indent << "percent_complete: ";
    Printer<float>::stream(s, indent + "  ", v.percent_complete);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_TREE_MESSAGE_ROBOTSTATUSCONTROLLERFEEDBACK_H
