// Generated by gencpp from file behavior_tree/RobotStatusControllerGoal.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_TREE_MESSAGE_ROBOTSTATUSCONTROLLERGOAL_H
#define BEHAVIOR_TREE_MESSAGE_ROBOTSTATUSCONTROLLERGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behavior_tree
{
template <class ContainerAllocator>
struct RobotStatusControllerGoal_
{
  typedef RobotStatusControllerGoal_<ContainerAllocator> Type;

  RobotStatusControllerGoal_()
    : dishwasher_id(0)  {
    }
  RobotStatusControllerGoal_(const ContainerAllocator& _alloc)
    : dishwasher_id(0)  {
  (void)_alloc;
    }



   typedef uint32_t _dishwasher_id_type;
  _dishwasher_id_type dishwasher_id;





  typedef boost::shared_ptr< ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStatusControllerGoal_

typedef ::behavior_tree::RobotStatusControllerGoal_<std::allocator<void> > RobotStatusControllerGoal;

typedef boost::shared_ptr< ::behavior_tree::RobotStatusControllerGoal > RobotStatusControllerGoalPtr;
typedef boost::shared_ptr< ::behavior_tree::RobotStatusControllerGoal const> RobotStatusControllerGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator1> & lhs, const ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator2> & rhs)
{
  return lhs.dishwasher_id == rhs.dishwasher_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator1> & lhs, const ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior_tree

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65bd9e09a531006f4ecdeabe719004b9";
  }

  static const char* value(const ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65bd9e09a531006fULL;
  static const uint64_t static_value2 = 0x4ecdeabe719004b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_tree/RobotStatusControllerGoal";
  }

  static const char* value(const ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"uint32 dishwasher_id  # Specify which dishwasher we want to use\n"
;
  }

  static const char* value(const ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dishwasher_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStatusControllerGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_tree::RobotStatusControllerGoal_<ContainerAllocator>& v)
  {
    s << indent << "dishwasher_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.dishwasher_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_TREE_MESSAGE_ROBOTSTATUSCONTROLLERGOAL_H
