// Generated by gencpp from file behavior_tree/RobotStatusControllerResult.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_TREE_MESSAGE_ROBOTSTATUSCONTROLLERRESULT_H
#define BEHAVIOR_TREE_MESSAGE_ROBOTSTATUSCONTROLLERRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behavior_tree
{
template <class ContainerAllocator>
struct RobotStatusControllerResult_
{
  typedef RobotStatusControllerResult_<ContainerAllocator> Type;

  RobotStatusControllerResult_()
    : total_dishes_cleaned(0)  {
    }
  RobotStatusControllerResult_(const ContainerAllocator& _alloc)
    : total_dishes_cleaned(0)  {
  (void)_alloc;
    }



   typedef uint32_t _total_dishes_cleaned_type;
  _total_dishes_cleaned_type total_dishes_cleaned;





  typedef boost::shared_ptr< ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStatusControllerResult_

typedef ::behavior_tree::RobotStatusControllerResult_<std::allocator<void> > RobotStatusControllerResult;

typedef boost::shared_ptr< ::behavior_tree::RobotStatusControllerResult > RobotStatusControllerResultPtr;
typedef boost::shared_ptr< ::behavior_tree::RobotStatusControllerResult const> RobotStatusControllerResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator1> & lhs, const ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator2> & rhs)
{
  return lhs.total_dishes_cleaned == rhs.total_dishes_cleaned;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator1> & lhs, const ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior_tree

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58faa44dda59c6545bea63ff57491cbe";
  }

  static const char* value(const ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58faa44dda59c654ULL;
  static const uint64_t static_value2 = 0x5bea63ff57491cbeULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_tree/RobotStatusControllerResult";
  }

  static const char* value(const ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"uint32 total_dishes_cleaned\n"
;
  }

  static const char* value(const ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.total_dishes_cleaned);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStatusControllerResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_tree::RobotStatusControllerResult_<ContainerAllocator>& v)
  {
    s << indent << "total_dishes_cleaned: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.total_dishes_cleaned);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_TREE_MESSAGE_ROBOTSTATUSCONTROLLERRESULT_H
