// Generated by gencpp from file behavior_tree/TurningAroundFeedback.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_TREE_MESSAGE_TURNINGAROUNDFEEDBACK_H
#define BEHAVIOR_TREE_MESSAGE_TURNINGAROUNDFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behavior_tree
{
template <class ContainerAllocator>
struct TurningAroundFeedback_
{
  typedef TurningAroundFeedback_<ContainerAllocator> Type;

  TurningAroundFeedback_()
    : rotation_status(0.0)  {
    }
  TurningAroundFeedback_(const ContainerAllocator& _alloc)
    : rotation_status(0.0)  {
  (void)_alloc;
    }



   typedef float _rotation_status_type;
  _rotation_status_type rotation_status;





  typedef boost::shared_ptr< ::behavior_tree::TurningAroundFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_tree::TurningAroundFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct TurningAroundFeedback_

typedef ::behavior_tree::TurningAroundFeedback_<std::allocator<void> > TurningAroundFeedback;

typedef boost::shared_ptr< ::behavior_tree::TurningAroundFeedback > TurningAroundFeedbackPtr;
typedef boost::shared_ptr< ::behavior_tree::TurningAroundFeedback const> TurningAroundFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_tree::TurningAroundFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_tree::TurningAroundFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior_tree::TurningAroundFeedback_<ContainerAllocator1> & lhs, const ::behavior_tree::TurningAroundFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.rotation_status == rhs.rotation_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior_tree::TurningAroundFeedback_<ContainerAllocator1> & lhs, const ::behavior_tree::TurningAroundFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior_tree

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behavior_tree::TurningAroundFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_tree::TurningAroundFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree::TurningAroundFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree::TurningAroundFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree::TurningAroundFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree::TurningAroundFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_tree::TurningAroundFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d86daa292f3a880c6162663bc037e95";
  }

  static const char* value(const ::behavior_tree::TurningAroundFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d86daa292f3a880ULL;
  static const uint64_t static_value2 = 0xc6162663bc037e95ULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_tree::TurningAroundFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_tree/TurningAroundFeedback";
  }

  static const char* value(const ::behavior_tree::TurningAroundFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_tree::TurningAroundFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"float32 rotation_status\n"
;
  }

  static const char* value(const ::behavior_tree::TurningAroundFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_tree::TurningAroundFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rotation_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurningAroundFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_tree::TurningAroundFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_tree::TurningAroundFeedback_<ContainerAllocator>& v)
  {
    s << indent << "rotation_status: ";
    Printer<float>::stream(s, indent + "  ", v.rotation_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_TREE_MESSAGE_TURNINGAROUNDFEEDBACK_H
