// Generated by gencpp from file behavior_tree/TurningAroundResult.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_TREE_MESSAGE_TURNINGAROUNDRESULT_H
#define BEHAVIOR_TREE_MESSAGE_TURNINGAROUNDRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behavior_tree
{
template <class ContainerAllocator>
struct TurningAroundResult_
{
  typedef TurningAroundResult_<ContainerAllocator> Type;

  TurningAroundResult_()
    : rotating_time(0)  {
    }
  TurningAroundResult_(const ContainerAllocator& _alloc)
    : rotating_time(0)  {
  (void)_alloc;
    }



   typedef uint32_t _rotating_time_type;
  _rotating_time_type rotating_time;





  typedef boost::shared_ptr< ::behavior_tree::TurningAroundResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_tree::TurningAroundResult_<ContainerAllocator> const> ConstPtr;

}; // struct TurningAroundResult_

typedef ::behavior_tree::TurningAroundResult_<std::allocator<void> > TurningAroundResult;

typedef boost::shared_ptr< ::behavior_tree::TurningAroundResult > TurningAroundResultPtr;
typedef boost::shared_ptr< ::behavior_tree::TurningAroundResult const> TurningAroundResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_tree::TurningAroundResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_tree::TurningAroundResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior_tree::TurningAroundResult_<ContainerAllocator1> & lhs, const ::behavior_tree::TurningAroundResult_<ContainerAllocator2> & rhs)
{
  return lhs.rotating_time == rhs.rotating_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior_tree::TurningAroundResult_<ContainerAllocator1> & lhs, const ::behavior_tree::TurningAroundResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior_tree

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behavior_tree::TurningAroundResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_tree::TurningAroundResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree::TurningAroundResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree::TurningAroundResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree::TurningAroundResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree::TurningAroundResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_tree::TurningAroundResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e884966b1d8cea170e6a1b0ac01e559";
  }

  static const char* value(const ::behavior_tree::TurningAroundResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e884966b1d8cea1ULL;
  static const uint64_t static_value2 = 0x70e6a1b0ac01e559ULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_tree::TurningAroundResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_tree/TurningAroundResult";
  }

  static const char* value(const ::behavior_tree::TurningAroundResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_tree::TurningAroundResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"uint32 rotating_time # 1 round, 2round or so on\n"
;
  }

  static const char* value(const ::behavior_tree::TurningAroundResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_tree::TurningAroundResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rotating_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurningAroundResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_tree::TurningAroundResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_tree::TurningAroundResult_<ContainerAllocator>& v)
  {
    s << indent << "rotating_time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.rotating_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_TREE_MESSAGE_TURNINGAROUNDRESULT_H
