// Generated by gencpp from file behavior_tree/TurningAroundActionGoal.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_TREE_MESSAGE_TURNINGAROUNDACTIONGOAL_H
#define BEHAVIOR_TREE_MESSAGE_TURNINGAROUNDACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <behavior_tree/TurningAroundGoal.h>

namespace behavior_tree
{
template <class ContainerAllocator>
struct TurningAroundActionGoal_
{
  typedef TurningAroundActionGoal_<ContainerAllocator> Type;

  TurningAroundActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  TurningAroundActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::behavior_tree::TurningAroundGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct TurningAroundActionGoal_

typedef ::behavior_tree::TurningAroundActionGoal_<std::allocator<void> > TurningAroundActionGoal;

typedef boost::shared_ptr< ::behavior_tree::TurningAroundActionGoal > TurningAroundActionGoalPtr;
typedef boost::shared_ptr< ::behavior_tree::TurningAroundActionGoal const> TurningAroundActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator1> & lhs, const ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator1> & lhs, const ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior_tree

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0849d4257e2ccdcdd7c3b5e64505fac";
  }

  static const char* value(const ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0849d4257e2ccdcULL;
  static const uint64_t static_value2 = 0xdd7c3b5e64505facULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_tree/TurningAroundActionGoal";
  }

  static const char* value(const ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"TurningAroundGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: behavior_tree/TurningAroundGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"uint32 rotation_direction \n"
;
  }

  static const char* value(const ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurningAroundActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_tree::TurningAroundActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::behavior_tree::TurningAroundGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_TREE_MESSAGE_TURNINGAROUNDACTIONGOAL_H
