// Generated by gencpp from file dockingrobot/Docking.msg
// DO NOT EDIT!


#ifndef DOCKINGROBOT_MESSAGE_DOCKING_H
#define DOCKINGROBOT_MESSAGE_DOCKING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dockingrobot
{
template <class ContainerAllocator>
struct Docking_
{
  typedef Docking_<ContainerAllocator> Type;

  Docking_()
    : left(0)
    , right(0)  {
    }
  Docking_(const ContainerAllocator& _alloc)
    : left(0)
    , right(0)  {
  (void)_alloc;
    }



   typedef uint32_t _left_type;
  _left_type left;

   typedef uint32_t _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::dockingrobot::Docking_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dockingrobot::Docking_<ContainerAllocator> const> ConstPtr;

}; // struct Docking_

typedef ::dockingrobot::Docking_<std::allocator<void> > Docking;

typedef boost::shared_ptr< ::dockingrobot::Docking > DockingPtr;
typedef boost::shared_ptr< ::dockingrobot::Docking const> DockingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dockingrobot::Docking_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dockingrobot::Docking_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dockingrobot::Docking_<ContainerAllocator1> & lhs, const ::dockingrobot::Docking_<ContainerAllocator2> & rhs)
{
  return lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dockingrobot::Docking_<ContainerAllocator1> & lhs, const ::dockingrobot::Docking_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dockingrobot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dockingrobot::Docking_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dockingrobot::Docking_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dockingrobot::Docking_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dockingrobot::Docking_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dockingrobot::Docking_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dockingrobot::Docking_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dockingrobot::Docking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d174ad098f607428d0ec6461248ca61";
  }

  static const char* value(const ::dockingrobot::Docking_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d174ad098f60742ULL;
  static const uint64_t static_value2 = 0x8d0ec6461248ca61ULL;
};

template<class ContainerAllocator>
struct DataType< ::dockingrobot::Docking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dockingrobot/Docking";
  }

  static const char* value(const ::dockingrobot::Docking_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dockingrobot::Docking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 left\n"
"uint32 right\n"
;
  }

  static const char* value(const ::dockingrobot::Docking_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dockingrobot::Docking_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Docking_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dockingrobot::Docking_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dockingrobot::Docking_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOCKINGROBOT_MESSAGE_DOCKING_H
